/*****PRODUCTS********/
export const PROJECT_REQUEST = 'PROJECT_REQUEST';
export const PROJECT_SUCCESS = 'PROJECT_SUCCESS';
export const PROJECT_FAIL = 'PROJECT_FAIL';
export const PROJECT_START = 'PROJECT_START';

export const PROJECT_DELETE_REQUEST = 'PROJECT_DELETE_REQUEST';
export const PROJECT_DELETE_SUCCESS = 'PROJECT_DELETE_SUCCESS';
export const PROJECT_DELETE_FAIL = 'PROJECT_DELETE_FAIL';

export const PROJECT_GET_DETAILS_REQUEST = 'PROJECT_GET_DETAILS_REQUEST';
export const PROJECT_UPDATE_REQUEST = 'PROJECT_UPDATE_REQUEST';
export const AUTH_UPDATE_PROJECT = 'AUTH_UPDATE_PROJECT';
export const PROJECT_GET_DETAILS_FAIL = 'PROJECT_GET_DETAILS_FAIL';
export const PROJECT_UPDATE_SUCCESS = 'PROJECT_UPDATE_SUCCESS';
export const PROJECT_UPDATE_FAIL = 'PROJECT_UPDATE_FAIL';

export const PROJECT_CREATE_REQUEST = 'PROJECT_CREATE_REQUEST';
export const PROJECT_CREATE_SUCCESS = 'PROJECT_CREATE_SUCCESS';
export const PROJECT_CREATE_FAIL = 'PROJECT_CREATE_FAIL';

export const PROJECT_GET_DETAILS_SUCCESS = 'PROJECT_GET_DETAILS_SUCCESS';
export const ADD_PROJECT_FILTER = 'ADD_PROJECT_FILTER';
export const DELETE_PROJECT_FILTER = 'DELETE_PROJECT_FILTER';

/*****CUSTOMER********/
export const CUSTOMER_REQUEST = 'CUSTOMER_REQUEST';
export const CUSTOMER_SUCCESS = 'CUSTOMER_SUCCESS';
export const CUSTOMER_FAIL = 'CUSTOMER_FAIL';
export const CUSTOMER_START = 'CUSTOMER_START';

export const CUSTOMER_DELETE_REQUEST = 'CUSTOMER_DELETE_REQUEST';
export const CUSTOMER_DELETE_SUCCESS = 'CUSTOMER_DELETE_SUCCESS';
export const CUSTOMER_DELETE_FAIL = 'CUSTOMER_DELETE_FAIL';

export const CUSTOMER_GET_DETAILS_REQUEST = 'CUSTOMER_GET_DETAILS_REQUEST';
export const CUSTOMER_CREATE_REQUEST = 'CUSTOMER_CREATE_REQUEST';
export const CUSTOMER_UPDATE_REQUEST = 'CUSTOMER_UPDATE_REQUEST';
export const CUSTOMER_GET_DETAIL_SUCCESS = 'CUSTOMER_GET_DETAIL_SUCCESS';
export const AUTH_UPDATE_CUSTOMER = 'AUTH_UPDATE_CUSTOMER';
export const CUSTOMER_GET_DETAILS_FAIL = 'CUSTOMER_GET_DETAILS_FAIL';
export const CUSTOMER_UPDATE_SUCCESS = 'CUSTOMER_UPDATE_SUCCESS';
export const CUSTOMER_UPDATE_FAIL = 'CUSTOMER_UPDATE_FAIL';
export const CUSTOMER_CREATE_SUCCESS = 'CUSTOMER_CREATE_SUCCESS';
export const CUSTOMER_CREATE_FAIL = 'CUSTOMER_CREATE_FAIL';
export const CUSTOMER_GET_DETAILS_SUCCESS = 'CUSTOMER_GET_DETAILS_SUCCESS';
export const ADD_CUSTOMER_FILTER = 'ADD_CUSTOMER_FILTER';
export const DELETE_CUSTOMER_FILTER = 'DELETE_CUSTOMER_FILTER';

// *************** LOGIN ***********************/
/*****AUTH********/
export const START_LOGIN = 'START_LOGIN';
export const REQUEST_LOGIN = 'REQUEST_LOGIN';
export const SUCCESS_LOGIN = 'SUCCESS_LOGIN';
export const ERROR_LOGIN = 'ERROR_LOGIN';
export const REQUEST_LOGOUT = 'REQUEST_LOGOUT';
// action for deleting the token.
export const DELETE_OAUTH_TOKEN = 'DELETE_OAUTH_TOKEN';
// action for saving the token.
export const SAVE_OAUTH_TOKEN = 'SAVE_OAUTH_TOKEN';

// action for saving the token.
export const UPDATE_USER_LOCATION = 'UPDATE_USER_LOCATION';
export const AUTH_UPDATE_USER = 'AUTH_UPDATE_USER';

//action for Client
export const CLIENT_CREATE_REQUEST = 'CLIENT_CREATE_REQUEST';
export const CLIENT_CREATE_SUCCESS = 'CLIENT_CREATE_SUCCESS';
export const CLIENT_CREATE_FAIL = 'CLIENT_CREATE_FAIL';
